import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }: any) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <Image src="" alt="" />
          <Link href="/">Home</Link>
          <Link href="/events">Events</Link>
          <Link href="/about-us">About Us</Link>
        </nav>
      </header>
      <main className={styles.main}>
        {data.map((ev: any) => (
          <a key={ev.id} href={`/events/${ev.id}`}>
            <Image width={200} height={'100'} src={ev.image} alt={ev.title} /> <h2> {ev.title} </h2> <p>{ev.description}</p>
          </a>
        ))}
      </main>

      <footer className={styles.footer}>
        <p>2023 Taras Ishchuk. Practical implementation Next.js React Course from FreeCodeCamp</p>
      </footer>
    </div>
  )
};

export async function getServerSideProps() {
  const { events_categories } = await import('../../data/data.json');

  return {
    props: {
      data: events_categories,
    }
  }
};
